### ISSUE TITLE
'org.axonframework.commandhandling.CommandBus' that could not be found

### ISSUE THREAD

**Issue by loonis** [AxonFramework/extension-reactor#111]
### Basic information

* Axon Framework version: 4.5
* JDK version:  17
* Reactor Extension version: 4.5.1
* spring-boot-starter-parent : 2.6.3

### Steps to reproduce

When starting a simple application I have this error : 

Parameter 0 of method reactiveCommandGateway in org.axonframework.extensions.reactor.autoconfig.ReactorAutoConfiguration required a bean of type 'org.axonframework.commandhandling.CommandBus' that could not be found.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.6.3</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.example</groupId>
  <artifactId>demo-reactor</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>demo-reactor</name>
  <description>demo-reactor</description>
  
  <properties>
    <java.version>17</java.version>
  </properties>
  
  <dependencies>
    
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.axonframework</groupId>
      <artifactId>axon-spring</artifactId>
      <version>4.5</version>
    </dependency>

    <dependency>
      <groupId>org.axonframework.extensions.reactor</groupId>
      <artifactId>axon-reactor-spring-boot-starter</artifactId>
      <version>4.5.1</version>
    </dependency>

  </dependencies>

</project>
```

```
import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import org.axonframework.modelling.command.AggregateLifecycle;
import org.axonframework.spring.stereotype.Aggregate;

@Aggregate
public class TestAggregate {

  @AggregateIdentifier
  private String id;
  private String data;

  public TestAggregate() {
  }

  @CommandHandler
  public TestAggregate(SimpleCommand simpleCommand) {
    AggregateLifecycle.apply(new SimpleEvent());
  }
}
```

**Comment by smcvb** [comment]
I'm guessing you're dealing with a versioning issue here, @loonis.

Would you (1) mind using the `axon-spring-boot-starter` dependency instead of the `axon-spring` dependency?
As you're using the reactor starter, I wager you also want the Framework starter.
That might just cause the missing `CommandBus` bean, as you haven't added the started to construct those.

And, would you (2) mind using the [Axon Bom](https://github.com/AxonFramework/axon-bom)? 
That'll ensure you're using versions of Axon's component that work with another.

Let us know whether that resolves your problems, @loonis.
Note that for problems in your setup, you can always go to our [forum](https://discuss.axoniq.io/), or StackOverflow with the `axon` tag, to discuss and resolve problems you're facing.
The issue tracker for any of Axon's repositories is intended for bugs and feature requests.

**Comment by loonis** [comment]
Hello @smcvb replacing `axon-spring` with `axon-spring-boot-starter` and adding the Axon Bom solve the problem.
Thank you for you quick reply.

**Comment by smcvb** [comment]
Awesome, happy to hear that solved your issues, @loonis!
